### ISSUE TITLE
Authentication error.

### ISSUE THREAD

**Issue by yz** [Longhanks/PyCloudKit#1]
Thanks for sharing, but getting 401 Authentication error.  Any suggestion?

**Comment by Longhanks** [comment]
Did you configure your app in CloudKit Dashboard for usage with a server-to-server key, upload your public key and configure your API key in pycloudkit_config.py?
After all, this just wraps the JSON web interface of CloudKit. You may want to read [this](cloudkit server to server).

**Comment by yz** [comment]
Thnx for the reply.  Yes, we followed the steps and getting the 401 Authentication error.  Is it working for you?

**Comment by Longhanks** [comment]
Have you tried composing the request via curl? Is that working? Earlier commits relied on calling the system's curl binary, do those work for you?

**Comment by yz** [comment]
We actually got it to work on the 2nd try using your latest version.  It works like a charm.  Now looking to  test uploading image assets.  Any suggestion?  Looks it require 2 steps, any easier way?
